### ISSUE TITLE
Search bar above my emptypad

### ISSUE THREAD

**Issue by sachiniyer** [aminoa/emptypad#3]
This project does not do what it purports to do - give me an empty pad. When I go to a deployment (e.g. https://emptypad.sachiniyer.com), I see some weird search bar above the and tabs above the empty pad.

This is a critical bug for me, and highly dissuades me from using the product.

I would like to see action on this soon @aminoa .

![Screenshot_20230214_193316](https://user-images.githubusercontent.com/38194905/218894735-ca596467-047e-417c-8d96-c35dd93eb0fe.png)

**Comment by aminoa** [comment]
Of course, due to browser restrictions, it is not possible to immediately hide the tabs and title bar. However, auto-fullscreen can be implemented.

**Comment by sachiniyer** [comment]
thx. looking forward.

**Comment by sachiniyer** [comment]
I have found another solution that enables auto full screen. I don't understand the technical limits @aminoa 

https://web.respondus.com/he/lockdownbrowser/

**Comment by aminoa** [comment]
The lockdown browser is proprietary so this software cannot be used for emptypad. Furthermore, one goal of this app is to be cross-platform; limiting the browsers allowed would be contrary to that goal. Your feedback is much appreciated.

**Comment by sachiniyer** [comment]
Okay I understand.
